### ISSUE TITLE
Load Inventory Dependency on Admin Account in Latest FUAM Version

### ISSUE THREAD

**Issue by AJGOLD062025** [microsoft/fabric-toolbox#191]
Hello all,

I recently installed the latest version of FUAM, expecting that the Load Inventory process would no longer depend on my personal Fabric admin account. However, I’m still encountering the following error (see below).

Since my admin account requires manual activation each time I use it, this poses a challenge for scheduling automated data loads. Notably, once I activate my admin account and run the process manually, it completes successfully — which suggests that account dependency is the issue.

All other loads run without relying on my admin account and work as expected.

Could you please advise on how I can configure Load Inventory to run independently of my admin account?

Thanks, Arron

**Error:**

<img width="1066" height="982" alt="Image" src="https://github.com/user-attachments/assets/85ce0499-1b2e-4d37-8fc5-d4b8c7542aa5" />

Full error message:
401 Unauthorized for url: https://api.fabric.microsoft.com/v1.0/myorg/admin/workspaces/modified?excludePersonalWorkspaces=True&excludeInActiveWorkspaces=True
Headers: {'Cache-Control': 'no-store, must-revalidate, no-cache', 'Pragma': 'no-cache', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/octet-stream', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'RequestId': 'd55c47d2-70d7-4fbc-bdd3-4b7b98a481d5', 'Access-Control-Expose-Headers': 'RequestId', 'request-redirected': 'true', 'home-cluster-uri': 'https://wabi-north-europe-f-primary-redirect.analysis.windows.net/', 'Date': 'Wed, 23 Jul 2025 05:26:25 GMT'}
401 Unauthorized for url: https://api.fabric.microsoft.com/v1.0/myorg/admin/workspaces/modified?excludePersonalWorkspaces=True&excludeInActiveWorkspaces=True
Headers: {'Cache-Control': 'no-store, must-revalidate, no-cache', 'Pragma': 'no-cache', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/octet-stream', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'RequestId': '5943c7d2-6d25-42c6-8cd5-306a90dc4168', 'Access-Control-Expose-Headers': 'RequestId', 'request-redirected': 'true', 'home-cluster-uri': 'https://wabi-north-europe-f-primary-redirect.analysis.windows.net/', 'Date': 'Wed, 23 Jul 2025 05:26:26 GMT'}
401 Unauthorized for url: https://api.fabric.microsoft.com/v1.0/myorg/admin/workspaces/modified?excludePersonalWorkspaces=True&excludeInActiveWorkspaces=True
Headers: {'Cache-Control': 'no-store, must-revalidate, no-cache', 'Pragma': 'no-cache', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/octet-stream', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'RequestId': '4edf1470-298f-434b-858d-38a25e779bfa', 'Access-Control-Expose-Headers': 'RequestId', 'request-redirected': 'true', 'home-cluster-uri': 'https://wabi-north-europe-f-primary-redirect.analysis.windows.net/', 'Date': 'Wed, 23 Jul 2025 05:26:26 GMT'}
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[35], line 7
      4 response = RequestWithRetry('get', f"v1.0/myorg/admin/workspaces/modified?excludePersonalWorkspaces={exclude_personal_workspaces}&excludeInActiveWorkspaces={exclude_inactive_workspaces}")
      6 # Build array buckets 
----> 7 modified_workspaces = pd.json_normalize(response.json())
      8 modified_workspaces["index"] = pd.to_numeric(modified_workspaces.reset_index()["index"])
      9 modified_workspaces["run"] = modified_workspaces["index"] // workspaces_per_request

AttributeError: 'NoneType' object has no attribute 'json'

**Comment by kethom-analytics** [comment]
Hello,

Have you tried to use the service principal instead?

Best regards
Kevin

**Comment by AJGOLD062025** [comment]
@kethom-analytics, I'm not sure where I get the 'name' details mentioned. I only have the client and tenant IDs. Would they work?

<img width="749" height="111" alt="Image" src="https://github.com/user-attachments/assets/d2a90167-46d5-44c1-ba2b-489937882bc4" />

**Comment by leo-19-stack** [comment]
Hi,
This started failing for me as well when I updated to FUAM 7.1. Even updating to 7.2 didn’t fix the issue.
Notebook was using the service principal until I updated the solution. Now it always tries to authenticate with the admin account instead (I also have to grant temporary permissions like AJGOLD, so that’s not a feasible solution). It says that it cannot find the key vault that I specify in the parameters. I double checked multiple times and the parameters are correct and pointing to the right vault.

Could it be something with the new 7 versions?

**Comment by AJGOLD062025** [comment]
@leo-19-stack, what details are you using in the parameters out of interest? I only have the ID's, is that what worked for you previously? I'd like to try this to see if it works my end:

details I have:
tenant = 'xxb2e961-xxxxxxxxxxxxxxxxxxxxxx'
client = 'xx0000f3-xxxxxxxxxxxxxxxxxxxxxxx'
client_secret = 'xxz8Q~xxxxxxxxxxxxxxxxxxxxxxx'
capacity_metrics_dataset_id = 'xxc70160-xxxxxxxxxxxxxxxxxxx'

**Comment by leo-19-stack** [comment]
In the parameters I use the names of the secrets that I have in my key vault, I don’t hard code directly the secret values in the parameters. Basically:

1. Key vault secrets store the values
2. Notebook use secret names to fetch the values from the vault

**Comment by AJGOLD062025** [comment]
Any help here?

**Comment by AJGOLD062025** [comment]
@ggintli @NickyvVr any help here guys? The **Load_Inventory** is still failing unless I use my admin account to run the whole pipeline.

<img width="1661" height="337" alt="Image" src="https://github.com/user-attachments/assets/31369a70-cd8b-432d-995d-3814fe2df562" />

**Comment by AJGOLD062025** [comment]
Anyone?

**Comment by NickyvVr** [comment]
@AJGOLD062025 I see you have a Service Principal, that should work.
If you need the name of your Keyvault, go to https://portal.azure.com/#browse/Microsoft.KeyVault%2Fvaults. You should be able to get the name of the KeyVault where your secrets are stored. Or otherwise ask for the name from IT.

**Comment by AJGOLD062025** [comment]
Thanks @NickyvVr.
Do I need to complete all the key vault details in the parameters for this to work? I now have the name from your link together with the following IDs (not names):

KEYVAULT NAME = damt-xxxxxx

tenant ID = 'aab2e961-XXXXXXXXXXXX'
client ID = '880000f3-XXXXXXXXXXXXX'
client_secret ID = 'Udz8Q~XXXXXXXXXXXX
capacity_metrics_dataset_id = '45c70160-XXXXXXXXXXX'

Should the keyvault name and the IDs be put into the parameters within the main Load_FUAM_Data_E2E:

<img width="741" height="481" alt="Image" src="https://github.com/user-attachments/assets/abd73b70-cdfe-4153-90e7-9e86c7f69a62" />

Thanks again for the great help here, our company are really loving this solution and I'd love to get this final issue solved.

**Comment by AJGOLD062025** [comment]
@NickyvVr, I think this has worked! thanks again for the inputs!

**Comment by ggintli** [comment]
Hello,

we close this issue, since a new version of FUAM has been deployed.

Please find the change log from FUAM here: https://github.com/microsoft/fabric-toolbox/blob/main/monitoring/fabric-unified-admin-monitoring/changelog/FUAM_Changelog.md

"How to update FUAM" here:
https://github.com/microsoft/fabric-toolbox/blob/main/monitoring/fabric-unified-admin-monitoring/how-to/How_to_update_FUAM.md

Best Regards,
ggintli
